---
- name: install packages on all servers
  hosts: all
  become: true
  tasks:
    - name: install packages
      apt: 
       name: ["default-jdk", "tree"]
       state: present
       update_cache: yes

